

export const Features=()=>{

    return(

        <>
        <div className="bg-gray-50 p-8 min-h-[350px] flex flex-col items-center justify-center font-sans">
      <h2 className="text-gray-800 text-3xl font-bold mb-16 text-center">Application Metrics</h2>
      <div className="grid lg:grid-cols-4 sm:grid-cols-2 gap-6 max-lg:gap-12">
        <div className="text-center">
          <h3 className="text-gray-800 text-4xl font-extrabold">5.4<span className="text-gold-500">M+</span></h3>
          <p className="text-base text-black font-bold mt-4">Total Customers</p>
          <p className="text-sm text-black mt-2">The total number of Customer in <span className="text-gold-500 font-extrabold">Chennai</span></p>
        </div>
        <div className="text-center">
          <h3 className="text-gray-800 text-4xl font-extrabold">$80<span className="text-gold-500">K</span></h3>
          <p className="text-base text-black font-bold mt-4">Franchise</p>
          <p className="text-sm text-black mt-2">The total revenue generated by the application.</p>
        </div>
        <div className="text-center">
          <h3 className="text-gray-800 text-4xl font-extrabold">100<span className="text-gold-500">K</span></h3>
          <p className="text-base text-black font-bold mt-4">Engagement</p>
          <p className="text-sm text-black mt-2">The level of user engagement with the application's content and features.</p>
        </div>
        <div className="text-center">
          <h3 className="text-gray-800 text-4xl font-extrabold">99.9<span className="text-gold-500">%</span></h3>
          <p className="text-base text-black font-bold mt-4">Gold Designs</p>
          <p className="text-sm text-black mt-2">The percentage of time the server has been operational and available.</p>
        </div>
      </div>
    </div>
        </>
    )
}